name: Deploy Prod

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  test:
    uses: .github/jobs/test-job.yml
  # !TODO: Доделать, когда будет хостинг
  # deploy:
  #   needs: test
  #   uses: ./.github/jobs/deploy-job.yml
  e2e:
    needs: test
    uses: .github/jobs/e2e-job.yml
    with:
      TEST_ENV_BASE_URL: https://orthosmir.ru
