name: Deploy Prod

on:
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]

jobs:
  # !TODO: Доделать, когда будет хостинг
  # deploy:
  #   needs: test
  #   uses: ./.github/workflows/job.deploy.yml
  e2e:
    needs: deploy
    uses: ./.github/workflows/job.e2e.yml
    with:
      TEST_ENV_BASE_URL: https://orthosmir.ru
